services:
  - type: web
    name: evsu-flask-app
    env: python
    region: ohio
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn login:app
    envVars:
      - key: DB_DRIVER
        value: "{ODBC Driver 17 for SQL Server}"
      - key: DB_SERVER
        value: your-cloud-sql-server.database.windows.net
      - key: DB_NAME
        value: evsuDB
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
    healthCheckPath: /health